### ISSUE TITLE
Release APK

### ISSUE THREAD

**Issue by rradar** [jleeuwes/home-assistant-android-without-google#1]
Hello @jleeuwes 

Thank's for your effort you put in this! I wonder if you could push a apk into the release section along with the source code? This would be wonderful :star_struck:

**Comment by grote** [comment]
Test APK for https://gitlab.com/grote/libre-assistant is available via https://grobox.de/fdroid/ until https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7079 was approved.

**Comment by jleeuwes** [comment]
There is now a build flavor of the official Home Assistant app without the proprietary stuff. That app will soon be in the F-Droid repository, see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7387 :partying_face:

My fork is now obsolete.
